CREATE TABLE IF NOT EXISTS `request_file` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`location` TEXT NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`name` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`request_id` BIGINT(19) NOT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `FK_REQUEST_FILE_REQUEST` (`request_id`) USING BTREE,
	CONSTRAINT `FK_REQUEST_FILE_REQUEST` FOREIGN KEY (`request_id`) REFERENCES `request` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
