CREATE TABLE IF NOT EXISTS `request_stage` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`description` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`realization_date` DATETIME(6) NOT NULL,
	`state` VARCHAR(12) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`owner_id` BIGINT(19) NOT NULL,
	`request_id` BIGINT(19) NOT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `FK_REQUEST_STAGE_USER` (`owner_id`) USING BTREE,
	INDEX `FK_REQUEST_STAGE_REQUEST` (`request_id`) USING BTREE,
	CONSTRAINT `FK_REQUEST_STAGE_REQUEST` FOREIGN KEY (`request_id`) REFERENCES `request` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_REQUEST_STAGE_USER` FOREIGN KEY (`owner_id`) REFERENCES `user` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
