server:
  port: 8080
  
# spring Configs  
spring:
  profiles:
    active: dev
    
#File property
  servlet:
    multipart:
      max-request-size: 2MB    

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_api_db?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
    
# Jackson Configs
  jackson:
    default-property-inclusion: NON_NULL

  jpa:
    hibernate: 
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    show-sql: true
    
# jwt spring security Configs 
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000     
        
# Flyway Configs
flyway:
  url: jdbc:mysql://localhost:3306/
  schemas: spring_api_db
  user: root
  password: admin123
    
#Swagger Configs
springdoc:
  pathsToMatch: 
    - /auth/**
    - /api/**
  swagger-ui:
    use-root-path: false
    
#AWS Properties
aws:
  s3:
    bucket-name: spring-api-files
    access-key: access-key
    secret-key: secret-key
    
    
#https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#appendix.application-properties.web    
      