# spring Configs  
spring:
  datasource:
    url: jdbc:mysql://spring-api-db.cpvixlzlkybo.us-east-1.rds.amazonaws.com:3306/spring_api_db?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin123
    
  jpa:
    show-sql: true